openapi: 3.0.0
info:
  title: CoWorkerMatch API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local Server
tags:
  - name: Users
    description: ユーザに関する操作
  - name: Hobbies
    description: 趣味に関する操作
  - name: UserHobbies
    description: ユーザの趣味に関する操作
  - name: Matches
    description: マッチングに関する操作
  - name: Questions
    description: 2択の質問に関する操作
  - name: Messages
    description: メッセージに関する操作

paths:
  /users:
    $ref: "./users/users.yaml#/paths/~1users"
  /users/{user_id}:
    $ref: "./users/users.yaml#/paths/~1users~1{user_id}"
  /hobbies:
    $ref: "./hobbies/hobbies.yaml#/paths/~1hobbies"
  /user_hobbies:
    $ref: "./user_hobbies/user_hobbies.yaml#/paths/~1user_hobbies"
  /user_hobbies/{user_id}:
    $ref: "./user_hobbies/user_hobbies.yaml#/paths/~1user_hobbies~1{user_id}"
  /matches:
    $ref: "./matches/matches.yaml#/paths/~1matches"
  /matches/{matching_id}:
    $ref: "./matches/matches.yaml#/paths/~1matches~1{matching_id}"
  /questions:
    $ref: "./questions/questions.yaml#/paths/~1questions"
  /messages/{matching_id}:
    $ref: "./messages/messages.yaml#/paths/~1messages~1{matching_id}"
